//! Loads and validates the three authored scenario datasets under `scenarios/v1/`, asserting they
//! deserialize, validate against [`limen_core::validate::validate_manifest`] with zero errors,
//! and meet the structural coverage bar required of every real scenario (see
//! `docs/SCENARIO_AUTHORING.md`). These files are generated by
//! `cargo run -p limen-core --example author_scenarios`; this test is the guard that catches any
//! drift between that generator and the checked-in JSON, or any authoring mistake the generator
//! itself does not know to check.
//!
//! Loads scenario content through [`limen_core::catalog::get_scenario`] -- the same embedded,
//! `include_str!`-backed source of truth the WASM adapter's `list_scenarios`/`get_scenario_detail`/
//! `run_trial` exports use -- rather than re-declaring parallel `include_str!` constants here.
//! This is deliberately redundant with `catalog`'s own
//! `every_embedded_scenario_validates_with_zero_errors` unit test (both assert zero
//! `validate_manifest` errors on the same three files): that one is a same-module sanity check
//! from the catalog's perspective, this one is the scenario-authoring structural-coverage guard
//! from the authoring/testing perspective, and keeping both is welcome redundant coverage from a
//! different angle rather than duplication to eliminate.

use std::collections::BTreeMap;

use limen_core::catalog::get_scenario;
use limen_core::model::ScenarioManifest;
use limen_core::validate::validate_manifest;

const MIN_ITEMS: usize = 12;
const MAX_ITEMS: usize = 16;
const MIN_REQUIRED_FACTS: usize = 8;
const MAX_REQUIRED_FACTS: usize = 10;
const MIN_DISTRACTORS: usize = 2;

fn load(expected_scenario_id: &str) -> ScenarioManifest {
    let manifest = get_scenario(expected_scenario_id).unwrap_or_else(|| {
        panic!("expected catalog::get_scenario to resolve '{expected_scenario_id}'")
    });
    assert_eq!(
        manifest.scenario_id, expected_scenario_id,
        "scenario_id must exactly match the required id/filename"
    );
    manifest
}

fn assert_validates_cleanly(manifest: &ScenarioManifest) {
    let errors = validate_manifest(manifest);
    assert!(
        errors.is_empty(),
        "expected zero validate_manifest errors for '{}', got:\n{:#?}",
        manifest.scenario_id,
        errors
    );
}

fn assert_structural_coverage(manifest: &ScenarioManifest) {
    let item_count = manifest.items.len();
    assert!(
        (MIN_ITEMS..=MAX_ITEMS).contains(&item_count),
        "'{}' has {item_count} items, expected {MIN_ITEMS}..={MAX_ITEMS}",
        manifest.scenario_id
    );

    // Sequential, 0-based order_index (checked here as a structural-coverage property; the
    // fixed set {0, 1, ..., n-1} is exactly what "sequential 0-based" means, independent of
    // each item's position in the `items` Vec).
    let mut order_indices: Vec<u32> = manifest.items.iter().map(|i| i.order_index).collect();
    order_indices.sort_unstable();
    let expected_order_indices: Vec<u32> = (0..item_count as u32).collect();
    assert_eq!(
        order_indices, expected_order_indices,
        "'{}' item order_index values must be exactly 0..{item_count}",
        manifest.scenario_id
    );

    let fact_count = manifest.annotations.required_facts.len();
    assert!(
        (MIN_REQUIRED_FACTS..=MAX_REQUIRED_FACTS).contains(&fact_count),
        "'{}' has {fact_count} required facts, expected {MIN_REQUIRED_FACTS}..={MAX_REQUIRED_FACTS}",
        manifest.scenario_id
    );

    let has_nonempty_contradiction_group = manifest
        .annotations
        .contradiction_groups
        .iter()
        .any(|group| !group.members.is_empty());
    assert!(
        has_nonempty_contradiction_group,
        "'{}' must have at least one non-empty contradiction group",
        manifest.scenario_id
    );

    let distractor_count = manifest.annotations.distractor_source_ids.len();
    assert!(
        distractor_count >= MIN_DISTRACTORS,
        "'{}' has {distractor_count} distractor_source_ids, expected at least {MIN_DISTRACTORS}",
        manifest.scenario_id
    );
}

/// For every [`limen_core::model::EvidenceSpan`] anywhere in the manifest (fact-component
/// evidence and contradiction-group members alike), asserts `text.get(byte_start..byte_end)` is
/// `Some` for the referenced source item -- i.e. every span is in-bounds and lands on codepoint
/// boundaries, and can never panic when sliced at trial-run time.
fn assert_every_evidence_span_is_a_valid_utf8_slice(manifest: &ScenarioManifest) {
    let items_by_id: BTreeMap<&str, &str> = manifest
        .items
        .iter()
        .map(|item| (item.source_id.as_str(), item.text.as_str()))
        .collect();

    let check = |source_id: &str, byte_start: u32, byte_end: u32, path: String| {
        let text = *items_by_id
            .get(source_id)
            .unwrap_or_else(|| panic!("{path}: references unknown source_id '{source_id}'"));
        assert!(
            text.get(byte_start as usize..byte_end as usize).is_some(),
            "{path}: span [{byte_start}, {byte_end}) is not a valid UTF-8 slice of source_id \
             '{source_id}' (text byte length {})",
            text.len()
        );
    };

    for (fi, fact) in manifest.annotations.required_facts.iter().enumerate() {
        for (ci, comp) in fact.components.iter().enumerate() {
            for (ei, span) in comp.evidence.iter().enumerate() {
                check(
                    &span.source_id,
                    span.byte_start,
                    span.byte_end,
                    format!(
                        "{}: required_facts[{fi}] ('{}') .components[{ci}] ('{}') .evidence[{ei}]",
                        manifest.scenario_id, fact.fact_id, comp.component_id
                    ),
                );
            }
        }
    }

    for (gi, group) in manifest.annotations.contradiction_groups.iter().enumerate() {
        for (mi, member) in group.members.iter().enumerate() {
            check(
                &member.source_id,
                member.byte_start,
                member.byte_end,
                format!(
                    "{}: contradiction_groups[{gi}] ('{}') .members[{mi}]",
                    manifest.scenario_id, group.group_id
                ),
            );
        }
    }
}

fn assert_scenario_is_sound(expected_scenario_id: &str) {
    let manifest = load(expected_scenario_id);
    assert_validates_cleanly(&manifest);
    assert_structural_coverage(&manifest);
    assert_every_evidence_span_is_a_valid_utf8_slice(&manifest);
}

#[test]
fn incident_investigation_is_valid_and_covers_required_structure() {
    assert_scenario_is_sound("incident-investigation");
}

#[test]
fn product_comparison_is_valid_and_covers_required_structure() {
    assert_scenario_is_sound("product-comparison");
}

#[test]
fn requirements_architecture_review_is_valid_and_covers_required_structure() {
    assert_scenario_is_sound("requirements-architecture-review");
}

/// Cross-scenario coverage that is only meaningful in aggregate: at least one composite fact
/// (`components.len() > 1`) and at least one component with genuinely redundant evidence
/// (`evidence.len() > 1`) somewhere across all three manifests combined.
#[test]
fn at_least_one_composite_fact_and_one_redundant_evidence_component_across_all_scenarios() {
    let manifests = [
        load("incident-investigation"),
        load("product-comparison"),
        load("requirements-architecture-review"),
    ];

    let composite_facts: Vec<(&str, &str)> = manifests
        .iter()
        .flat_map(|m| {
            m.annotations
                .required_facts
                .iter()
                .filter(|f| f.components.len() > 1)
                .map(move |f| (m.scenario_id.as_str(), f.fact_id.as_str()))
        })
        .collect();
    assert!(
        !composite_facts.is_empty(),
        "expected at least one composite fact (components.len() > 1) across all three scenarios"
    );

    let redundant_components: Vec<(&str, &str, &str)> = manifests
        .iter()
        .flat_map(|m| {
            m.annotations.required_facts.iter().flat_map(move |f| {
                f.components
                    .iter()
                    .filter(|c| c.evidence.len() > 1)
                    .map(move |c| {
                        (
                            m.scenario_id.as_str(),
                            f.fact_id.as_str(),
                            c.component_id.as_str(),
                        )
                    })
            })
        })
        .collect();
    assert!(
        !redundant_components.is_empty(),
        "expected at least one FactComponent with evidence.len() > 1 (redundant evidence) across \
         all three scenarios"
    );
}
